<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BackupUsersSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
         [
            'id' => 2,
            'name' => 'M. SULHAN ZIDNY',
            'email' => 'sulhansyah22@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$bzv0flvW/fBsY58S4ClqWelwDJfRxXVwNZTXz.vr5qtR/SnAxBm2m',
            'remember_token' => NULL,
            'created_at' => '2025-01-26 13:32:11',
            'updated_at' => '2025-01-26 13:32:11',
            'deleted_at' => null,
         ],
         [
            'id' => 3,
            'name' => 'Yosi',
            'email' => 'ikiemaileyosi@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$HnZC1ywLx8dkPo9WZmsFvuRo8DacS9Ni0SVkHPfVFZtULsX6iXawm',
            'remember_token' => NULL,
            'created_at' => '2025-01-26 16:11:40',
            'updated_at' => '2025-01-26 16:11:40',
            'deleted_at' => null,
         ],
         [
            'id' => 4,
            'name' => 'Han',
            'email' => 'han@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$SH4lsHbby.HnxHbarfe/QeA8Zz7PhO1T78SXLHeovFzoQYl7G7bMG',
            'remember_token' => NULL,
            'created_at' => '2025-02-07 09:22:49',
            'updated_at' => '2025-02-10 13:04:20',
            'deleted_at' => null,
         ],
         [
            'id' => 5,
            'name' => 'Gus Muin',
            'email' => 'mr.muin@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$NBdTiaQpEwgPgSll3XNK4eo6OU0cImX8oy0ltjjZNTxQfMvs9J/qm',
            'remember_token' => NULL,
            'created_at' => '2025-02-10 02:24:15',
            'updated_at' => '2025-02-10 18:51:20',
            'deleted_at' => null,
         ],
         [
            'id' => 6,
            'name' => 'Sayyed menolak rezim prabowo',
            'email' => 'amir@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$lgxKaH4s35ip/XxvKPddzOn5FpgVHX03cIxl2BY2S6hP42vUpKZgu',
            'remember_token' => NULL,
            'created_at' => '2025-02-10 02:30:32',
            'updated_at' => '2025-02-10 02:30:32',
            'deleted_at' => null,
         ],
         [
            'id' => 7,
            
            'name' => 'El Gasing',
            'email' => 'tzyman3@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$Rwzq3h/9eRLfAtQ./BNYF.41enYfFte.TEM7oEzWIdG9oh1gkveFm',
            'remember_token' => NULL,
            'created_at' => '2025-02-10 04:12:12',
            'updated_at' => '2025-02-10 04:12:12',
            'deleted_at' => null,
         ],
         [
            'id' => 8,
            
            'name' => 'Guest',
            'email' => 'guest@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$8S7a80FuRzW/.KX57udxVuk/PwfFA32kbhTz2Z4WTeax5dN/SYR1G',
            'remember_token' => NULL,
            'created_at' => '2025-02-10 12:43:09',
            'updated_at' => '2025-02-10 12:43:09',
            'deleted_at' => null,
         ],
         [
            'id' => 9,
            
            'name' => 'Badut',
            'email' => 'badut@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$KE5neKVvkyf8UIjKpmdkauz5cog/N9nUqFdXgUCAOk1XeM.YiPHZK',
            'remember_token' => NULL,
            'created_at' => '2025-02-10 18:39:28',
            'updated_at' => '2025-02-10 18:39:28',
            'deleted_at' => null,
         ], 
         [
            'id' => 15,
            
            'name' => 'Badut1',
            'email' => 'badut1@gmail.com',
            'birth_date' => NULL,
            'address' => NULL,
            'phone_number' => NULL,
            'left_date' => NULL,
            'status' => 'active',
            'email_verified_at' => NULL,
            'password' => '$2y$12$YPwgEUYTAdnPoqbsZUnOkeMo.6ug2zE6O1tp529vbcTh4ki4e7iK.',
            'remember_token' => NULL,
            'created_at' => '2025-02-24 17:41:10',
            'updated_at' => '2025-02-24 17:55:59',
            'deleted_at' => NULL,
         ],
         ]);
    }
}